### ISSUE TITLE
SIGSEV when using results with iterators and `Natural`

### ISSUE THREAD

**Issue by gmega** [arnetheduck/nim-results#38]
I'm seeing a crash in our code when combining `nim-results` with Chronos (head) and [Natural](https://nim-lang.org/docs/system.html#Natural). I'm running Linux, `nim 1.6.18`, and `nim-results` HEAD. I was able to unpack this into a minimal example which doesn't involve Chronos:

```nim
import pkg/results

type R = Result[Natural, ref CatchableError]

type ValueHolder = ref object of RootObj
  result*: R

proc transfer(holder: ValueHolder, value: sink R) = 
  holder.result = move(value)

var iter = iterator (holder: ValueHolder): int {.closure.} =
  var value = R.ok(1.Natural)
  transfer(holder, move(value))
  GC_fullCollect()

var holder = ValueHolder()
discard iter(holder)
echo $holder.result.value
```
This code will result in a `SIGSEGV: Illegal storage access. (Attempt to read from nil?)` in my system. Any of the following will fix the issue:
1. removing the call to `move` in `transfer(holder, move(value))` (i.e. make it `transfer(holder, value)`);
2. using `int` instead of `Natural`.

Looking at the C code, there is one tiny difference in how the offending `move` gets compiled when using `int` vs `Natural` (which there shouldn't be, if I understand this right). For `int`, I get:

```c
nimZeroMem((void *)(&T4_), sizeof(tyObject_Result__KsaqI9a9aXbsuy9bC0eVP9aOHQ));
nimCopyMem((void *)(&T4_), (NIM_CONST void *)(&(*colonenvP_).value1), sizeof(T4_));
switch ((*colonenvP_).value1.oResultPrivate)
{
   case NIM_FALSE:
      unsureAsgnRef((void **)&(*colonenvP_).value1._oResultPrivate_1.eResultPrivate, NIM_NIL);
      break;
   case NIM_TRUE:
      (*colonenvP_).value1._oResultPrivate_2.vResultPrivate = 0;
      break;
}
(*colonenvP_).value1.oResultPrivate = 0;
```
For `Natural`, OTOH, I get:
```c
nimZeroMem((void *)(&T4_), sizeof(tyObject_Result__iR58GIqAJSNnhcSbFUya9bw));
nimCopyMem((void *)(&T4_), (NIM_CONST void *)(&(*colonenvP_).value1), sizeof(T4_));
switch ((*colonenvP_).value1.oResultPrivate)
{
   case NIM_FALSE:
      unsureAsgnRef((void **)&(*colonenvP_).value1._oResultPrivate_1.eResultPrivate, NIM_NIL);
      break;
   case NIM_TRUE:
      break;
}
(*colonenvP_).value1.oResultPrivate = 0;
```
meaning, there is one missing line when I use `Natural`:
```c
(*colonenvP_).value1._oResultPrivate_2.vResultPrivate = 0;
```
adding this line to the C code and compiling it directly seems to fix the crash, but I have no idea why. I'm not even sure this is an issue with `nim-results`, but thought I'd post it here.

**Comment by gmega** [comment]
OK this is likely a compiler bug, related to this https://github.com/nim-lang/Nim/issues/22462. I just did the version tests and it starts crashing in 1.4.0 (works with 1.2.0), will dig deeper.

**Comment by dryajov** [comment]
This sounds more like a compiler bug/issue.

**Comment by gmega** [comment]
Yep, after some digging I'm more and more convinced that it is. Gonna file a report in nim-lang and close this one.

**Comment by gmega** [comment]
Closing in favour of https://github.com/nim-lang/Nim/issues/23214.

**Comment by arnetheduck** [comment]
fwiw, the fix makes sense: when the `Result` has a `ref` error type and is partially reset, the `Natural` value it had that shares memory area with the error gets treated as a `ref` after resetting the ok/err flag.
